name: scan_assistant
description: 润农扫码激活辅助软件
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.0
  audioplayers: ^5.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.2
  image_picker: ^1.0.0
  image: ^4.1.0
  google_mlkit_barcode_scanning: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
